name: 'linux_server'
description: 'A sample command-line application.'
version: '0.0.0'
homepage: 'https://github.com/azkadev/general'
repository: 'https://github.com/azkadev/linux'
issue_tracker: 'https://github.com/azkadev/general/issues'
documentation: 'https://github.com/azkadev/linux/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.2.3'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
